services:
  postgres:
    image: postgres:16-alpine
    container_name: dmqt_postgres
    environment:
      POSTGRES_USER: dmqt
      POSTGRES_PASSWORD: dmqt
      POSTGRES_DB: dmqt
    ports:
      - "5432:5432" # Ez KRITIKUS: így éred el kívülről (Windows-ról)
    volumes:
      - pgdata:/var/lib/postgresql/data

  kroki:
    image: yuzutech/kroki
    container_name: dmqt_kroki
    environment:
      - KROKI_MERMAID_HOST=kroki-mermaid
    ports:
      - "8000:8000"
    depends_on:
      - kroki-mermaid

  kroki-mermaid:
    image: yuzutech/kroki-mermaid
    container_name: dmqt_kroki_mermaid
    expose:
      - "8002"

volumes:
  pgdata: