services:
  postgres:
    image: postgres:16-alpine
    container_name: dmqt_postgres
    environment:
      POSTGRES_USER: dmqt
      POSTGRES_PASSWORD: dmqt
      POSTGRES_DB: dmqt
    ports:
      - "5432:5432" # Ez KRITIKUS: így éred el kívülről (Windows-ról)
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: